### ISSUE TITLE
announce.php

### ISSUE THREAD

**Issue by zimm794** [kaitokid222/pdonvtracker#5]
Die function hex2bin($hexdata) gibt es doch nicht mehr.

**Comment by kaitokid222** [comment]
php.net hat geholfen
http://php.net/manual/de/function.hex2bin.php

> jannik [dot] zappe [at] udo [dot] edu
```
if (!function_exists('hex2bin')){
	function hex2bin($str) {
		$sbin = "";
		$len = strlen($str);
		for ($i=0;$i<$len;$i+=2) {
			$sbin .= pack( "H*", substr( $str, $i, 2 ) );
		}
		return $sbin;
	}
}
```

aber in der announce ist die Funktion bereits vorhanden und alle php-funktionen dort sind php7-kompatibel

```
function hex2bin($hexdata) {
    for ($i=0;$i<strlen($hexdata);$i+=2) {
        $bindata.=chr(hexdec(substr($hexdata,$i,2)));
    }
   return $bindata;
}
```

kannst du das genauer erklären?

**Comment by zimm794** [comment]
http://www.netvision-technik.de/forum/showthread.php?t=7465&highlight=hex2bin

**Comment by kaitokid222** [comment]
http://www.netvision-technik.de/forum/showpost.php?p=83111&postcount=15
https://github.com/kaitokid222/pdonvtracker/commit/b11f37ad0b15910658f4c5fa21e6ca465ea54496

**Comment by zimm794** [comment]
Ok, super.

**Comment by kaitokid222** [comment]
wenn du mehr findest, fühle dich gerne eingeladen, tickets rauszuhauen bis die tastatur glüht, denn ich brauche jede hilfe die ich kriegen kann. :alien:
