### ISSUE TITLE
Announce Management 

### ISSUE THREAD

**Issue by Saugjunkie** [kaitokid222/pdonvtracker#7]
Hallo 

Da du ja so fleißig bist was ich richtig geil finde möchte ich gerne etwas anraten und zwar leuft die announce seperat zur NV source. Wurde es gut finden wenn man dann die announce per klick starten bzw stoppen kann im falle eines Ausfall es oder Fehlers. Dazu vielleicht noch ne status Seite mit paar statistiken

**Comment by kaitokid222** [comment]
Das werde ich auf jeden Fall nach "endgültiger" Fertigstellung des SocketServers in Angriff nehmen, würde mich aber auch für nen Pull begeistern können. immerhin weißt du am besten wie du dir das vorstellst.

**Comment by kaitokid222** [comment]
kommt mit dem SocketServer 1.0 Update, wenn ich die gesamte NV-funktionalität dort abgebildet habe. mir fehlen noch waittime ect, weil ich gestern erst die zwei-wege-kommunikation mit dem tracker gebaut habe.
![ruvgoihltmeseemnvwiaxg](https://user-images.githubusercontent.com/33453552/34639264-1fdd1ec6-f2dd-11e7-8615-42c66f2cea27.png)

![ascb2dl8sms7i2xfl8q9ya](https://user-images.githubusercontent.com/33453552/34639250-d6485b2c-f2dc-11e7-8152-1438f2b79c9d.png)
