### ISSUE TITLE
Fatal Error in include/class/polls.php

### ISSUE THREAD

**Issue by Saugjunkie** [kaitokid222/pdonvtracker#8]
da wollte ich glatt mal die source testen und hab sie gleich in meinen webserver geschmissen kahm sofort dieser fehler Fatal error: 'break' not in the 'loop' or 'switch' context in /home/users/bt-technik/www/nv/include/class/polls.php on line 67 und die seite blieb weiss

nachdem ich dann in meinem debian 9 die announce angeschmissen habe spamt diese gleich 
PHP Notice:  Only variables should be passed by reference in /home/users/bt-technik/www/nv/announce/core/server.class.php on line 44 das ist zwar nur eine notice nervt aber trotzdem wenn die log damit voll gemacht wird.

MFG
Saugjunkie

**Comment by kaitokid222** [comment]
Probiere bitte mal die "1.0er" Version von der Socketannounce und gib mir die aktuelle Zeilennummer für diese notice. 🥇

**Comment by Saugjunkie** [comment]
if(socket_select($read,$write = NULL, $except = NULL, $tv_sec = 5) < 1){
			return true;
		}

zeile 44-46

**Comment by Saugjunkie** [comment]
Der fehler ist nun weg und die index.php laesst sich aufrufen.

**Comment by kaitokid222** [comment]
oder mach mal nen stfu-operator davor und/oder post die zeile

**Comment by Saugjunkie** [comment]
von welcher php da wo die notice kommt? das ist diese zeile hier aus der server.class.php zeile 44-46

if(socket_select($read,$write = NULL, $except = NULL, $tv_sec = 5) < 1){
			return true;
		}

**Comment by kaitokid222** [comment]
mach mal

```php
$write = NULL;
$except = NULL;
if(socket_select($read, $write, $except, $tv_sec = 5) < 1){
	return true;
}

**Comment by Saugjunkie** [comment]
okay die notice kommt nicht mehr aber dadurch sehe ich etwas anderes in der console

root@server001:/home/saugjunkie/pdonvtracker/announce# php server.php
PHP Warning:  file_get_contents(http://localhost:80/saconf.php?socket=1&operator=admin): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
 in /home/saugjunkie/pdonvtracker/announce/core/nv.class.php on line 119
PHP Warning:  Invalid argument supplied for foreach() in /home/saugjunkie/pdonvtracker/announce/core/nv.class.php on line 122
Server (212.48.117.36:81) gestartet

das sind die zeilen 118-122

public function GetNvConfig(){
119->		$response = file_get_contents($this->pdonvtracker . "/saconf.php?socket=1&operator=admin");
		$res_arr = json_decode($response, true);
		$na = array();
122->		foreach($res_arr["config"]["BAN_PEERIDS"] as $banc)
			$na[] = urldecode($banc);
		unset($res_arr["config"]["BAN_PEERIDS"]);
		$res_arr["config"]["BAN_PEERIDS"] = $na;
		$this->pdonvtracker_conf_arr = $res_arr;
	}

also den fehler aus zeile 119 konnte ich nachvollziehen gehoehrt aber meiner meinung nach auch in die config. da der parameter dazu akuell in der server.php in zeile 19 steht 
$nv->SetTrackerPath("localhost");
hab das localhost durch meine url ersetzt und dann war der fehler weg. es tat sich aber dann ein neuer auf.
PHP Notice:  Undefined index: BAN_PEERIDS in /home/saugjunkie/pdonvtracker/announce/core/nv.class.php on line 122
PHP Warning:  Invalid argument supplied for foreach() in /home/saugjunkie/pdonvtracker/announce/core/nv.class.php on line 122

**Comment by kaitokid222** [comment]
https://github.com/kaitokid222/pdonvtracker/blob/759b96aa92df80d89aa4fd1b696f9f0d3dc4d443/include/config.php#L334

Wird hier
https://github.com/kaitokid222/pdonvtracker/blob/759b96aa92df80d89aa4fd1b696f9f0d3dc4d443/saconf.php#L28

für die Reise zum Socketserver vorbereitet.
