### ISSUE TITLE
signup.php

### ISSUE THREAD

**Issue by Saugjunkie** [kaitokid222/pdonvtracker#9]
Notice: Veraltete Funktion dbconn wurde aufgerufen! in /home/users/bt-technik/www/nv/include/bittorrent.php on line 156

Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /home/users/bt-technik/www/nv/include/bittorrent.php:157 Stack trace: #0 /home/users/bt-technik/www/nv/signup.php(30): dbconn() #1 {main} thrown in /home/users/bt-technik/www/nv/include/bittorrent.php on line 157

Hier steht noch in der signup.php das dbcon drinn ersetzt man aber nun das dbcon mit userlogin(); in zeile 30 der signup.php bekommt man den unteren fehler.
Notice: A session had already been started - ignoring session_start() in /home/users/bt-technik/www/nv/signup.php on line 32

Fatal error: Uncaught Error: Call to undefined function mysql_query() in /home/users/bt-technik/www/nv/signup.php:35 Stack trace: #0 {main} thrown in /home/users/bt-technik/www/nv/signup.php on line 35

zeile 32-40 signup.php

session_start();

35 ->    $res = mysql_query("SELECT COUNT(*) FROM users") or sqlerr(__FILE__, __LINE__);
    $arr = mysql_fetch_row($res);
    if ($arr[0] >= $GLOBALS["MAX_USERS"]) {
            $_SESSION["proofcode"] = "";
            stderr("Sorry", "Das aktuelle Benutzerlimit (" . number_format($GLOBALS["MAX_USERS"]) . ") wurde erreicht. Inactive Accounts werden regelmäßig gelöscht, versuche es also einfach später nochmal...");
    }

das session_start(); kann ja da weg da ja schon vorher laut info eine sessions gestartet wurde. dann bleibt aber immer noch  der besagte fehler 
Fatal error: Uncaught Error: Call to undefined function mysql_query() in /home/users/bt-technik/www/nv/signup.php:35 Stack trace: #0 {main} thrown in /home/users/bt-technik/www/nv/signup.php on line 35

**Comment by kaitokid222** [comment]
#3 
Es ist ein langwieriger Prozess alle queries umzustellen. wenn du dir die source um jetztigen zustand anschauen willst, nimm php >= 5.3.0 && <= 7.0.0

lediglich die socket-announce ist 1.0
aber es können noch strict standard-errors wie der andere mit socket_select() auftreten #8 

ich habe nur eine testumgebung, aber sobald alle "relikte" wie mysql beseitigt sind upgrade ich auf php 7+ und bereinige dann nach strict standard
